### ISSUE TITLE
More details about inpainted image

### ISSUE THREAD

**Issue by Arcxml** [W-Ted/GScream#3]
Hello, in your paper you mentioned: The in-painted images are obtained by SD-inpainting and LaMa. Could you tell me more details? I used SD-inapinting but it didn't achieve the remove effect, but added a lot of other things.

**Comment by W-Ted** [comment]
Hello, Arcxml. 
When an unwanted object is introduced into the image by SD-inpainting, we will repeat the in-painting process until getting a reasonable in-painted reference, following this paper: https://arxiv.org/pdf/2304.09677.
