### ISSUE TITLE
Question on Model Performance with 360-Degree Scenes

### ISSUE THREAD

**Issue by minyan8** [W-Ted/GScream#7]
Hi, I noticed that you've tested the model on forward-facing scenes, and it performs well. I'm curious whether your model performs equally well on 360-degree scenes. Have you tried it on any 360-degree scenes before? I ran some tests, but the results weren't great, possibly because I might not be using the model correctly.

Here are my results:

PSNR: 19.7550
LPIPS: 0.2665
FID: 281.6104

**Comment by W-Ted** [comment]
Hi, @minyan8. 
The 360-degree scenes may exceed the capabilities of GScream. Our method inherently relies on the presence of a reference view for information borrowing, but one reference view may not offer adequate information for inpainting the 360-degree scene.

**Comment by wangmiaowei** [comment]
yes, same stuff not good for 360View.
